name: Run PHPUnit Tests

on:
  push:
    branches:
      - master

jobs:
  run_phpunit_tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.3.0
        env:
          MYSQL_SERVERNAME: db
          MYSQL_DATABASE: red
          MYSQL_USER: root
          MYSQL_PASSWORD: root_password
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - name: ps 1
        run: docker ps
      - name: Levantar contenedor MySQL
        run: docker run -d --name mysql-8.3.0  \
          -e MYSQL_ROOT_PASSWORD=root_password \
          -e MYSQL_DATABASE=red \
          -p 3306:3306 \
          pestan/red_pps:mysql-8.3.0
      - name: Levantar contenedor PHPMyAdmin
        run: docker run -d --name phpmyadmin-latest -p 8080:80 pestan/red_pps:phpmyadmin-latest
      - name: Levantar contenedor Apache PHP
        run: docker run -d --name php-8.2-apache -p 8000:80 pestan/red_pps:php-8.2-apache
      - name: ps 2
        run: docker ps -a
      - name: logs mysql
        run: docker logs mysql-8.3.0
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit html/tests/pruebasRegistro.php






