name: PHP Composer and PHPUnit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Establece la versión de PHP a 8.2

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit html/test
