name: PHP Composer and PHPUnit

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
        DB_HOST: db
        DB_DATABASE: red
        DB_USERNAME: root
        DB_PASSWORD: root_password
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u pestan --password-stdin

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Pull Docker web
        run: docker pull pestan/red_pps:php-8.2-apache
      - name: Pull Docker phpmyadmin
        run: docker pull pestan/red_pps:phpmyadmin-latest
      - name: Pull Docker db
        run: docker pull pestan/red_pps:mysql-8.3.0

      - name: Pull Docker web
        run: docker push pestan/red_pps:php-8.2-apache
      - name: Pull Docker phpmyadmin
        run: docker push pestan/red_pps:phpmyadmin-latest
      - name: Pull Docker db
        run: docker push pestan/red_pps:mysql-8.3.0
        
      - name: Pull Docker web
        run: docker run pestan/red_pps:php-8.2-apache
      - name: Pull Docker phpmyadmin
        run: docker run pestan/red_pps:phpmyadmin-latest
      - name: Pull Docker db
        run: docker run pestan/red_pps:mysql-8.3.0
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Run test suite
        run: vendor/bin/phpunit html/tests/pruebasRegistro.php